# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv = pd.read_csv("../output_data/citydata.csv")
csv

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Ribeira Grande,38.5167,-28.7000,24.22,88,75,2.57,PT,1658761328
1,Albany,42.6001,-73.9662,23.08,93,100,3.09,US,1658761202
2,Ugoofaaru,5.6667,73.0000,27.76,78,80,6.96,MV,1658761356
3,Rikitea,-23.1203,-134.9692,23.92,73,23,8.62,PF,1658761358
4,Lebu,-37.6167,-73.6500,12.22,82,100,10.87,CL,1658761359
...,...,...,...,...,...,...,...,...,...
541,Husavik,66.0449,-17.3389,11.67,73,34,4.35,IS,1658762035
542,Bianzhuang,34.8486,118.0447,24.61,90,1,4.32,CN,1658762036
543,Kieta,-6.2167,155.6333,25.73,85,42,2.34,PG,1658762037
544,Shahreza,32.0339,51.8794,34.26,7,10,6.28,IR,1658762039
545,Paamiut,61.9940,-49.6678,6.83,87,4,1.56,GL,1658762040

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Store latitude and longitude in locations
locations = csv[["Lat", "Lng"]]

Hum = csv["Humidity"]

In [4]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=Hum, 
                                 dissipating=True, max_intensity=150,
                                 point_radius=15)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
Hotel_df = csv.loc[(csv['Max Temp'] >= 21.1111) & (csv['Max Temp'] <= 26.66666667) & (csv['Wind Speed'] <= 10) & (csv['Cloudiness'] == 0), :]
Hotel_df['Hotel Name'] = ''
Hotel_df

C:\Users\johnm\AppData\Local\Temp/ipykernel_12444/1011330185.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotel_df['Hotel Name'] = ''

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
37,Aras,42.5617,-2.3560,26.23,36,0,3.60,ES,1658761401,
95,Portland,45.5234,-122.6762,21.38,68,0,2.57,US,1658761298,
105,Lagoa Formosa,-18.7786,-46.4075,25.57,30,0,2.73,BR,1658761489,
128,Adamantas,36.7333,24.4333,24.56,77,0,5.82,GR,1658761518,
136,Luanda,-8.8368,13.2343,23.00,78,0,4.12,AO,1658761529,
210,Castanheira de Pêra,40.0072,-8.2105,26.56,26,0,5.74,PT,1658761624,
310,Niagara Falls,43.1001,-79.0663,22.70,66,0,7.20,CA,1658761729,
353,Bereda,43.2686,-7.5406,26.52,38,0,2.53,ES,1658761789,
403,Mocuba,-16.8392,36.9856,21.94,53,0,3.86,MZ,1658761854,
483,Weiser,44.2510,-116.9693,24.07,48,0,0.89,US,1658761959,
494,Soledade,-28.8183,-52.5103,21.91,63,0,2.39,BR,1658761973,
503,Visby,57.6409,18.2960,25.12,38,0,8.23,SE,1658761984,

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [9]:
#target_coordinates = "-20.7377, 116.8463"
target_radius = 5000
target_type = "lodging"
target_search = "Hotel"


parameters = {
    'keyword': target_search,
    'radius': target_radius,
    'type': target_type,
    'key': g_key
}

url = f'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

print('Finding Hotels')     
print('-----------------------------')
for index, row in Hotel_df.iterrows():
    
    #grab type
    target_lat = row['Lat']
    target_lng = row['Lng']
    place = row['City']
    
    #inserts into parameters
    parameters['location'] = f"{target_lat}, {target_lng}"
    
    response = requests.get(url, params=parameters).json()
    
    #grab results
    results = response['results']
    
    try:
        #extract information
        Hotel_df.loc[index, 'Hotel Name'] = results[0]["name"]
        print(f'Found a hotel in {place}')
        
    except (KeyError, IndexError):
        print(f'no hotel available in {place}')
        
print("-----------------------------")
print("Data Retrieval Complete")   
print("-----------------------------")

Finding Hotels
-----------------------------
Found a hotel in Aras
Found a hotel in Portland
Found a hotel in Lagoa Formosa
Found a hotel in Adamantas
Found a hotel in Luanda
Found a hotel in Castanheira de Pêra
Found a hotel in Niagara Falls
Found a hotel in Bereda
Found a hotel in Mocuba
Found a hotel in Weiser
Found a hotel in Soledade
Found a hotel in Visby
-----------------------------
Data Retrieval Complete
-----------------------------

In [10]:
Hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
37,Aras,42.5617,-2.3560,26.23,36,0,3.60,ES,1658761401,Palacio de Pujadas by MIJ
95,Portland,45.5234,-122.6762,21.38,68,0,2.57,US,1658761298,River's Edge Hotel
105,Lagoa Formosa,-18.7786,-46.4075,25.57,30,0,2.73,BR,1658761489,Lagoa Hotel
128,Adamantas,36.7333,24.4333,24.56,77,0,5.82,GR,1658761518,Blue Rooms Hotel
136,Luanda,-8.8368,13.2343,23.00,78,0,4.12,AO,1658761529,"InterContinental Luanda Miramar, an IHG Hotel"
210,Castanheira de Pêra,40.0072,-8.2105,26.56,26,0,5.74,PT,1658761624,Restaurante Europa
310,Niagara Falls,43.1001,-79.0663,22.70,66,0,7.20,CA,1658761729,DoubleTree by Hilton Hotel Niagara Falls New York
353,Bereda,43.2686,-7.5406,26.52,38,0,2.53,ES,1658761789,Casa Grande de Anllo
403,Mocuba,-16.8392,36.9856,21.94,53,0,3.86,MZ,1658761854,Pensão Venus
483,Weiser,44.2510,-116.9693,24.07,48,0,0.89,US,1658761959,Weiser Motel & RV Park
494,Soledade,-28.8183,-52.5103,21.91,63,0,2.39,BR,1658761973,Hotel Ágata
503,Visby,57.6409,18.2960,25.12,38,0,8.23,SE,1658761984,Clarion Hotel Wisby

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in Hotel_df.iterrows()]
locate = Hotel_df[["Lat", "Lng"]]
marker_layer = gmaps.marker_layer(locate, info_box_content=hotel_info)

In [12]:
# Add marker layer ontop of heat map
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))